Repository project-chi/chi-editor, pull requests merged in 2022-11, with the labels that each got.

#9 Switch Python version and add setup instructions
  README.md
  pyproject.toml
Labels: bug, documentation

#10 Add the object scaling adapter
  chi_editor/canvas_adapter/__init__.py
  chi_editor/canvas_adapter/adapter.py
  chi_editor/canvas_adapter/entity.py
Labels: enhancement

#14 Update instructions
  README.md
Labels: documentation
